---
title: "Capstone Debate Scrape"
author: "Will Baldwin"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(quanteda)
library(textdata)
library(genius)
library(ggplot2)
library(ggalt)
library(tidyr)
library(tidytext)
library(tidyverse)
library(rvest)
library(plotly)
```

```{r, include=FALSE}
dict <- data_dictionary_LSD2015

url <- ("https://www.presidency.ucsb.edu/documents/republican-candidates-debate-cleveland-ohio")
debate1 <- read_html(url)
participants1 <- "BUSH|CARSON|CHRISTIE|CRUZ|HUCKABEE|KASICH|PAUL|RUBIO|TRUMP|WALKER|BAIER|KELLY|WALLACE"
participantsRemove1 <- "BUSH:|CARSON:|CHRISTIE:|CRUZ:|HUCKABEE:|KASICH:|PAUL:|RUBIO:|TRUMP:|WALKER:|BAIER:|KELLY:|WALLACE:"
```

```{r, include = FALSE}
scrape_transcript <- function(debate, participants, participantsRemove) {
    transcript <- debate %>% 
      html_nodes("div.field-docs-content") %>%
      html_text()
    
    transcript <- transcript %>%
      str_replace_all("[\n]", "")
    
    markers <- str_locate_all(transcript, pattern = participants)
    
    matches <- str_extract_all(transcript, participants)
    
    markers <- markers[[1]]
    matches <- matches[[1]]
    markersIndex <- markers[,1]
    n <- length(markersIndex)
    
    df <- data.frame(line = integer(n),
                     text = character(n),                      
                     speaker = character(n)
                     )
    
    for (i in 1:(length(markersIndex)-1)) {
      df$line[i] <- i
      df$text[i] <- substr(transcript,markersIndex[i],markersIndex[i+1]-1)
      df$speaker[i] <- matches[i]
      
    }
    
    df$text <- df$text %>%
      str_remove_all(participantsRemove)
    
    return(df)
}
```

### Using Bing Sentiment Dictionary
```{r, include = FALSE}
debate1DF <- scrape_transcript(debate1, participants1, participantsRemove1)

dumbellDf <- debate1DF %>%
  unnest_tokens(word, text) %>%
  group_by(speaker, word) %>%
  count() %>%
  ungroup(word) %>%
  mutate(
    total = sum(n),
  ) %>%
  inner_join(get_sentiments("bing")) %>%
  ungroup(speaker) %>%
  group_by(speaker, sentiment, total) %>%
  count() %>%
  mutate(
    percent = n/total * 100
  ) %>% 
  ungroup(speaker, sentiment, total) %>% spread(sentiment, percent) %>%
  group_by(speaker) %>% 
  fill(negative, positive) %>% 
  filter(!is.na(negative), !is.na(positive)) %>%
  mutate(
    difference = positive - negative
  )
```

```{r, echo = FALSE}

blue <- "#0171CE"
red <- "#DE4433"

debate1DF %>%
  unnest_tokens(word, text) %>%
  group_by(speaker, word) %>%
  count() %>%
  ungroup(word) %>%
  mutate(
    total = sum(n),
  ) %>%
  inner_join(get_sentiments("bing")) %>%
  ungroup(speaker) %>%
  group_by(speaker, sentiment, total) %>%
  count() %>%
  mutate(
    percent = n/total * 100
  ) %>%
  ggplot(mapping = aes(x = fct_reorder(speaker, percent), y = percent, fill =sentiment)) + 
  geom_col() + coord_flip() + labs(title = "Emotive language used in first 2016 GOP Primary Debate", x = "speaker", y = "emotive language as % of total words", subtitle = "Cruz appears to have used the most emotive language") + scale_fill_manual(values = c(red, blue)) + theme_bw()+
theme(
 # panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  panel.border=element_blank(),
  plot.title=element_text(size = 16, face="bold"),
  plot.title.position = "plot",
  plot.subtitle=element_text(face="italic", size=12, margin=margin(b=12)),
  plot.caption=element_text(size=8, margin=margin(t=12), color="#7a7d7e")
)

dumbellDf %>%
  ggplot() +
  geom_segment(aes(y = fct_reorder(speaker, difference), yend = speaker, x = 0.5, xend = 2.5), color = "#b2b2b2", size = 0.15) +
  geom_dumbbell(aes(y = fct_reorder(speaker, difference), x = positive, xend = negative), size=1.5, color="#b2b2b2", size_x=3, size_xend = 3, colour_x = blue, colour_xend = red) +
  geom_text(data = filter(dumbellDf, speaker == "RUBIO"), 
            aes(x = negative, y = speaker, label = "Negative"), 
            color = red, size = 2.5, fontface = "bold", vjust = -1)+
  geom_text(data = filter(dumbellDf, speaker == "RUBIO"), 
            aes(x = positive, y = speaker, label = "Positive"), 
            color = blue, size = 2.5, fontface = "bold", vjust = -1) +
  geom_text(aes(x = negative, y = speaker, label = round(negative, digits = 2)), color = red, size = 2.5, vjust = 1.5) +
  geom_text(aes(x = positive, y = speaker, label = round(positive, digits = 2)), color = blue, size = 2.5, vjust = 1.5) +
  geom_rect(aes(xmin = 2.55, xmax = 2.95, ymin = -Inf, ymax = Inf), fill = "grey") +
  geom_text(aes(label = paste0(round(difference, digits = 2), "%"), y = speaker, x = 2.75), size = 2.5)  +
  geom_text(data = filter(dumbellDf, speaker == "RUBIO"), aes(x = 2.73, y = speaker, label = "Difference"), color = "black", size = 2.5, vjust = -.78, fontface = "bold") + labs(x = "emotive language as % of total words", y = "speaker", title = "Sentiment differences in first 2016 GOP Primary Debate", subtitle = "Rubio exhibits the greatest preference for positive diction (Bing Sentiment Dictionary)" ) + theme_bw()+
theme(
 # panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  panel.border=element_blank(),
  plot.title=element_text(size = 16, face="bold"),
  plot.title.position = "plot",
  plot.subtitle=element_text(face="italic", size=12, margin=margin(b=12)),
  plot.caption=element_text(size=8, margin=margin(t=12), color="#7a7d7e")
)
```
### Using Lexicoder Sentiment Dictionary and NRC sentiment dictionary
```{r}
totalWords <- debate1DF %>%
  unnest_tokens(word, text) %>%
  group_by(speaker) %>%
  count() %>%
  rename(total = n)


lsdDf <- dfm(debate1DF$text, dictionary = data_dictionary_LSD2015)

newLsdDf <- convert(lsdDf, to = "data.frame")

newLsdDf$doc_id <- debate1DF$speaker

dumbellDFLSD <- newLsdDf %>%
  select(doc_id, positive, negative) %>%
  group_by(doc_id) %>%
  summarise(positive = sum(positive), negative = sum(negative)) %>%
  inner_join(totalWords, by = c("doc_id" = "speaker")) %>%
  rename(speaker = doc_id) %>%
  mutate(positive = positive/total * 100,
         negative = negative/total * 100,
         difference = positive - negative) 

barDFNRC <- debate1DF %>%
  unnest_tokens(word, text) %>%
  group_by(speaker, word) %>%
  count() %>%
  ungroup(word) %>%
  mutate(
    total = sum(n),
  ) %>%
  inner_join(get_sentiments("nrc")) %>%
  ungroup(speaker) %>%
  group_by(speaker, sentiment, total) %>%
  count() %>%
  mutate(
    percent = n/total * 100
  ) 
```


```{r}

barDFNRC %>%
  ggplot(mapping = aes(x = fct_reorder(speaker, percent), y = percent, fill =sentiment)) + 
  geom_col() + coord_flip() + labs(title = "Emotive language used in first 2016 GOP Primary Debate (NRC)", x = "speaker", y = "emotive language as % of total words", subtitle = "Cruz appears to have used the most emotive language")  + theme_bw()+
theme(
 # panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  panel.border=element_blank(),
  plot.title=element_text(size = 16, face="bold"),
  plot.title.position = "plot",
  plot.subtitle=element_text(face="italic", size=12, margin=margin(b=12)),
  plot.caption=element_text(size=8, margin=margin(t=12), color="#7a7d7e")
)

dumbellDFLSD %>%
  ggplot() +
  geom_segment(aes(y = fct_reorder(speaker, difference), yend = speaker, x = 0.5, xend = 6.5), color = "#b2b2b2", size = 0.15) +
  geom_dumbbell(aes(y = fct_reorder(speaker, difference), x = positive, xend = negative), size=1.5, color="#b2b2b2", size_x=3, size_xend = 3, colour_x = blue, colour_xend = red) +
  geom_text(data = filter(dumbellDf, speaker == "KASICH"), 
            aes(x = 1.82, y = speaker, label = "Negative"), 
            color = red, size = 2.5, fontface = "bold", vjust = -1)+
  geom_text(data = filter(dumbellDf, speaker == "KASICH"), 
            aes(x = 5.32, y = speaker, label = "Positive"), 
            color = blue, size = 2.5, fontface = "bold", vjust = -1) +
  geom_text(aes(x = negative, y = speaker, label = round(negative, digits = 2)), color = red, size = 2.5, vjust = 1.5) +
  geom_text(aes(x = positive, y = speaker, label = round(positive, digits = 2)), color = blue, size = 2.5, vjust = 1.5) +
  geom_rect(aes(xmin = 6.45, xmax = 7.05, ymin = -Inf, ymax = Inf), fill = "grey") +
  geom_text(aes(label = paste0(round(difference, digits = 2), "%"), y = speaker, x = 6.75), size = 2.5)  +
  geom_text(data = filter(dumbellDf, speaker == "KASICH"), aes(x = 6.75, y = speaker, label = "Difference"), color = "black", size = 2.5, vjust = -.78, fontface = "bold") + labs(x = "emotive language as % of total words", y = "speaker", title = "Sentiment differences in first 2016 GOP Primary Debate (Lexicoder Sentiment Dictionary)", subtitle = "Rubio exhibits the greatest preference for positive diction" ) + theme_bw()+
theme(
 # panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  panel.border=element_blank(),
  plot.title=element_text(size = 16, face="bold"),
  plot.title.position = "plot",
  plot.subtitle=element_text(face="italic", size=12, margin=margin(b=12)),
  plot.caption=element_text(size=8, margin=margin(t=12), color="#7a7d7e")
)
```

### Average Sentence Length

```{r}

debate1DF %>% 
  unnest_tokens(sentence, text, token = "sentences") %>%
  mutate(id = row_number()) %>%
  unnest_tokens(word, sentence) %>%
  group_by(id, speaker) %>%
  count() %>%
  ungroup(id) %>%
  summarize(avg_length = mean(n)) %>% 
  ggplot(mapping = aes(x = fct_reorder(speaker, avg_length), y = avg_length)) +
  geom_col() + coord_flip()

```
